// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "categories.proto" (package "personal_ledger", syntax proto3)
// tslint:disable
//
//-- ./proto/categories.proto
//
//
// Categories service protocol buffer definitions for the Personal Ledger backend.
// This file defines the gRPC API for managing financial categories, including CRUD,
// batch operations, filtering, and activation/deactivation.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CategoriesService } from "./categories";
import type { CategoryDeactivateResponse } from "./categories";
import type { CategoryDeactivateRequest } from "./categories";
import type { CategoryActivateResponse } from "./categories";
import type { CategoryActivateRequest } from "./categories";
import type { CategoriesDeleteBatchResponse } from "./categories";
import type { CategoriesDeleteBatchRequest } from "./categories";
import type { CategoryDeleteResponse } from "./categories";
import type { CategoryDeleteRequest } from "./categories";
import type { CategoryUpdateResponse } from "./categories";
import type { CategoryUpdateRequest } from "./categories";
import type { CategoriesListResponse } from "./categories";
import type { CategoriesListRequest } from "./categories";
import type { CategoryGetBySlugResponse } from "./categories";
import type { CategoryGetBySlugRequest } from "./categories";
import type { CategoryGetByCodeResponse } from "./categories";
import type { CategoryGetByCodeRequest } from "./categories";
import type { CategoryGetResponse } from "./categories";
import type { CategoryGetRequest } from "./categories";
import type { CategoriesCreateBatchResponse } from "./categories";
import type { CategoriesCreateBatchRequest } from "./categories";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CategoryCreateResponse } from "./categories";
import type { CategoryCreateRequest } from "./categories";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * gRPC service for managing financial categories.
 * Provides CRUD, batch, lookup, filtering, and activation operations.
 *
 * @generated from protobuf service personal_ledger.CategoriesService
 */
export interface ICategoriesServiceClient {
    /**
     * Create a new category.
     *
     * @generated from protobuf rpc: CategoryCreate
     */
    categoryCreate(input: CategoryCreateRequest, options?: RpcOptions): UnaryCall<CategoryCreateRequest, CategoryCreateResponse>;
    /**
     * Create multiple categories in a single request.
     *
     * @generated from protobuf rpc: CategoriesCreateBatch
     */
    categoriesCreateBatch(input: CategoriesCreateBatchRequest, options?: RpcOptions): UnaryCall<CategoriesCreateBatchRequest, CategoriesCreateBatchResponse>;
    /**
     * Get a category by its unique ID.
     *
     * @generated from protobuf rpc: CategoryGet
     */
    categoryGet(input: CategoryGetRequest, options?: RpcOptions): UnaryCall<CategoryGetRequest, CategoryGetResponse>;
    /**
     * Get a category by its unique code.
     *
     * @generated from protobuf rpc: CategoryGetByCode
     */
    categoryGetByCode(input: CategoryGetByCodeRequest, options?: RpcOptions): UnaryCall<CategoryGetByCodeRequest, CategoryGetByCodeResponse>;
    /**
     * Get a category by its URL slug.
     *
     * @generated from protobuf rpc: CategoryGetBySlug
     */
    categoryGetBySlug(input: CategoryGetBySlugRequest, options?: RpcOptions): UnaryCall<CategoryGetBySlugRequest, CategoryGetBySlugResponse>;
    /**
     * List categories with optional filtering, pagination, and sorting.
     *
     * @generated from protobuf rpc: CategoriesList
     */
    categoriesList(input: CategoriesListRequest, options?: RpcOptions): UnaryCall<CategoriesListRequest, CategoriesListResponse>;
    /**
     * Update an existing category (partial updates supported).
     *
     * @generated from protobuf rpc: CategoryUpdate
     */
    categoryUpdate(input: CategoryUpdateRequest, options?: RpcOptions): UnaryCall<CategoryUpdateRequest, CategoryUpdateResponse>;
    /**
     * Delete a category by ID.
     *
     * @generated from protobuf rpc: CategoryDelete
     */
    categoryDelete(input: CategoryDeleteRequest, options?: RpcOptions): UnaryCall<CategoryDeleteRequest, CategoryDeleteResponse>;
    /**
     * Delete multiple categories by their IDs.
     *
     * @generated from protobuf rpc: CategoriesDeleteBatch
     */
    categoriesDeleteBatch(input: CategoriesDeleteBatchRequest, options?: RpcOptions): UnaryCall<CategoriesDeleteBatchRequest, CategoriesDeleteBatchResponse>;
    /**
     * Activate a category (set is_active = true).
     *
     * @generated from protobuf rpc: CategoryActivate
     */
    categoryActivate(input: CategoryActivateRequest, options?: RpcOptions): UnaryCall<CategoryActivateRequest, CategoryActivateResponse>;
    /**
     * Deactivate a category (set is_active = false).
     *
     * @generated from protobuf rpc: CategoryDeactivate
     */
    categoryDeactivate(input: CategoryDeactivateRequest, options?: RpcOptions): UnaryCall<CategoryDeactivateRequest, CategoryDeactivateResponse>;
}
/**
 * gRPC service for managing financial categories.
 * Provides CRUD, batch, lookup, filtering, and activation operations.
 *
 * @generated from protobuf service personal_ledger.CategoriesService
 */
export class CategoriesServiceClient implements ICategoriesServiceClient, ServiceInfo {
    typeName = CategoriesService.typeName;
    methods = CategoriesService.methods;
    options = CategoriesService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Create a new category.
     *
     * @generated from protobuf rpc: CategoryCreate
     */
    categoryCreate(input: CategoryCreateRequest, options?: RpcOptions): UnaryCall<CategoryCreateRequest, CategoryCreateResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryCreateRequest, CategoryCreateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Create multiple categories in a single request.
     *
     * @generated from protobuf rpc: CategoriesCreateBatch
     */
    categoriesCreateBatch(input: CategoriesCreateBatchRequest, options?: RpcOptions): UnaryCall<CategoriesCreateBatchRequest, CategoriesCreateBatchResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoriesCreateBatchRequest, CategoriesCreateBatchResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get a category by its unique ID.
     *
     * @generated from protobuf rpc: CategoryGet
     */
    categoryGet(input: CategoryGetRequest, options?: RpcOptions): UnaryCall<CategoryGetRequest, CategoryGetResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryGetRequest, CategoryGetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get a category by its unique code.
     *
     * @generated from protobuf rpc: CategoryGetByCode
     */
    categoryGetByCode(input: CategoryGetByCodeRequest, options?: RpcOptions): UnaryCall<CategoryGetByCodeRequest, CategoryGetByCodeResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryGetByCodeRequest, CategoryGetByCodeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get a category by its URL slug.
     *
     * @generated from protobuf rpc: CategoryGetBySlug
     */
    categoryGetBySlug(input: CategoryGetBySlugRequest, options?: RpcOptions): UnaryCall<CategoryGetBySlugRequest, CategoryGetBySlugResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryGetBySlugRequest, CategoryGetBySlugResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * List categories with optional filtering, pagination, and sorting.
     *
     * @generated from protobuf rpc: CategoriesList
     */
    categoriesList(input: CategoriesListRequest, options?: RpcOptions): UnaryCall<CategoriesListRequest, CategoriesListResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoriesListRequest, CategoriesListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Update an existing category (partial updates supported).
     *
     * @generated from protobuf rpc: CategoryUpdate
     */
    categoryUpdate(input: CategoryUpdateRequest, options?: RpcOptions): UnaryCall<CategoryUpdateRequest, CategoryUpdateResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryUpdateRequest, CategoryUpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Delete a category by ID.
     *
     * @generated from protobuf rpc: CategoryDelete
     */
    categoryDelete(input: CategoryDeleteRequest, options?: RpcOptions): UnaryCall<CategoryDeleteRequest, CategoryDeleteResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryDeleteRequest, CategoryDeleteResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Delete multiple categories by their IDs.
     *
     * @generated from protobuf rpc: CategoriesDeleteBatch
     */
    categoriesDeleteBatch(input: CategoriesDeleteBatchRequest, options?: RpcOptions): UnaryCall<CategoriesDeleteBatchRequest, CategoriesDeleteBatchResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoriesDeleteBatchRequest, CategoriesDeleteBatchResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Activate a category (set is_active = true).
     *
     * @generated from protobuf rpc: CategoryActivate
     */
    categoryActivate(input: CategoryActivateRequest, options?: RpcOptions): UnaryCall<CategoryActivateRequest, CategoryActivateResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryActivateRequest, CategoryActivateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Deactivate a category (set is_active = false).
     *
     * @generated from protobuf rpc: CategoryDeactivate
     */
    categoryDeactivate(input: CategoryDeactivateRequest, options?: RpcOptions): UnaryCall<CategoryDeactivateRequest, CategoryDeactivateResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<CategoryDeactivateRequest, CategoryDeactivateResponse>("unary", this._transport, method, opt, input);
    }
}
