// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "categories.proto" (package "personal_ledger", syntax proto3)
// tslint:disable
//
//-- ./proto/categories.proto
//
//
// Categories service protocol buffer definitions for the Personal Ledger backend.
// This file defines the gRPC API for managing financial categories, including CRUD,
// batch operations, filtering, and activation/deactivation.
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { FieldMask } from "./google/protobuf/field_mask";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * Represents a financial category, such as an expense or asset type.
 * Used for organizing transactions and accounts.
 *
 * @generated from protobuf message personal_ledger.Category
 */
export interface Category {
    /**
     * Unique identifier (UUID) for the category.
     *
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * Short unique code for the category (e.g., "GROCERY").
     *
     * @generated from protobuf field: string code = 2
     */
    code: string;
    /**
     * Human-readable name of the category.
     *
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * Optional description of the category's purpose.
     *
     * @generated from protobuf field: optional string description = 4
     */
    description?: string;
    /**
     * Optional URL-friendly slug for the category (e.g., "groceries").
     *
     * @generated from protobuf field: optional string url_slug = 5
     */
    urlSlug?: string;
    /**
     * The type of category (asset, expense, etc.).
     *
     * @generated from protobuf field: personal_ledger.CategoryTypes category_type = 6
     */
    categoryType: CategoryTypes;
    /**
     * Optional HEX color code for UI display (e.g., "#FF0000").
     *
     * @generated from protobuf field: optional string color = 7
     */
    color?: string;
    /**
     * Optional icon name or URL for UI display.
     *
     * @generated from protobuf field: optional string icon = 8
     */
    icon?: string;
    /**
     * Whether the category is active and available for use.
     *
     * @generated from protobuf field: bool is_active = 9
     */
    isActive: boolean;
    /**
     * Timestamp when the category was created (UTC).
     *
     * @generated from protobuf field: google.protobuf.Timestamp created_on = 10
     */
    createdOn?: Timestamp;
    /**
     * Timestamp when the category was last updated (UTC).
     *
     * @generated from protobuf field: google.protobuf.Timestamp updated_on = 11
     */
    updatedOn?: Timestamp;
}
/**
 * Request to create a new category.
 *
 * @generated from protobuf message personal_ledger.CategoryCreateRequest
 */
export interface CategoryCreateRequest {
    /**
     * The category to create (id is ignored).
     *
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Response containing the created category.
 *
 * @generated from protobuf message personal_ledger.CategoryCreateResponse
 */
export interface CategoryCreateResponse {
    /**
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Request to fetch a category by its unique ID.
 *
 * @generated from protobuf message personal_ledger.CategoryGetRequest
 */
export interface CategoryGetRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * Response containing the requested category.
 *
 * @generated from protobuf message personal_ledger.CategoryGetResponse
 */
export interface CategoryGetResponse {
    /**
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Request to fetch a category by its unique code.
 *
 * @generated from protobuf message personal_ledger.CategoryGetByCodeRequest
 */
export interface CategoryGetByCodeRequest {
    /**
     * @generated from protobuf field: string code = 1
     */
    code: string;
}
/**
 * Response containing the requested category by code.
 *
 * @generated from protobuf message personal_ledger.CategoryGetByCodeResponse
 */
export interface CategoryGetByCodeResponse {
    /**
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Request to fetch a category by its URL slug.
 *
 * @generated from protobuf message personal_ledger.CategoryGetBySlugRequest
 */
export interface CategoryGetBySlugRequest {
    /**
     * @generated from protobuf field: string url_slug = 1
     */
    urlSlug: string;
}
/**
 * Response containing the requested category by slug.
 *
 * @generated from protobuf message personal_ledger.CategoryGetBySlugResponse
 */
export interface CategoryGetBySlugResponse {
    /**
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Request to list categories with optional pagination, filtering, and sorting.
 *
 * @generated from protobuf message personal_ledger.CategoriesListRequest
 */
export interface CategoriesListRequest {
    /**
     * The number of categories to skip (for pagination).
     *
     * @generated from protobuf field: int32 offset = 1
     */
    offset: number;
    /**
     * The maximum number of categories to return.
     *
     * @generated from protobuf field: int32 limit = 2
     */
    limit: number;
    /**
     * Optional filter by category type.
     *
     * @generated from protobuf field: optional personal_ledger.CategoryTypes category_type = 3
     */
    categoryType?: CategoryTypes;
    /**
     * Optional filter by active status.
     *
     * @generated from protobuf field: optional bool is_active = 4
     */
    isActive?: boolean;
    /**
     * Optional field to sort by (e.g., "created_on").
     *
     * @generated from protobuf field: optional string sort_by = 5
     */
    sortBy?: string;
    /**
     * Whether to sort in descending order.
     *
     * @generated from protobuf field: optional bool sort_desc = 6
     */
    sortDesc?: boolean;
}
/**
 * Response containing a list of categories and pagination info.
 *
 * @generated from protobuf message personal_ledger.CategoriesListResponse
 */
export interface CategoriesListResponse {
    /**
     * The list of categories matching the request.
     *
     * @generated from protobuf field: repeated personal_ledger.Category categories = 1
     */
    categories: Category[];
    /**
     * Total number of categories matching the filter (for pagination).
     *
     * @generated from protobuf field: int32 total_count = 2
     */
    totalCount: number;
    /**
     * The offset used in the request.
     *
     * @generated from protobuf field: int32 offset = 3
     */
    offset: number;
    /**
     * The limit used in the request.
     *
     * @generated from protobuf field: int32 limit = 4
     */
    limit: number;
}
/**
 * Request to update an existing category.
 *
 * @generated from protobuf message personal_ledger.CategoryUpdateRequest
 */
export interface CategoryUpdateRequest {
    /**
     * The ID of the category to update.
     *
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * The new category data (id is ignored).
     *
     * @generated from protobuf field: personal_ledger.Category category = 2
     */
    category?: Category;
    /**
     * Optional field mask to specify which fields to update.
     *
     * @generated from protobuf field: google.protobuf.FieldMask update_mask = 3
     */
    updateMask?: FieldMask;
}
/**
 * Response containing the updated category.
 *
 * @generated from protobuf message personal_ledger.CategoryUpdateResponse
 */
export interface CategoryUpdateResponse {
    /**
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Request to create multiple categories in a batch.
 *
 * @generated from protobuf message personal_ledger.CategoriesCreateBatchRequest
 */
export interface CategoriesCreateBatchRequest {
    /**
     * The categories to create (ids are ignored).
     *
     * @generated from protobuf field: repeated personal_ledger.Category categories = 1
     */
    categories: Category[];
}
/**
 * Response containing the created categories and count.
 *
 * @generated from protobuf message personal_ledger.CategoriesCreateBatchResponse
 */
export interface CategoriesCreateBatchResponse {
    /**
     * The created categories.
     *
     * @generated from protobuf field: repeated personal_ledger.Category categories = 1
     */
    categories: Category[];
    /**
     * The number of categories created.
     *
     * @generated from protobuf field: int32 created_count = 2
     */
    createdCount: number;
}
/**
 * Request to delete a category by ID.
 *
 * @generated from protobuf message personal_ledger.CategoryDeleteRequest
 */
export interface CategoryDeleteRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * Response indicating how many rows were deleted (should be 0 or 1).
 *
 * @generated from protobuf message personal_ledger.CategoryDeleteResponse
 */
export interface CategoryDeleteResponse {
    /**
     * @generated from protobuf field: int32 rows_deleted = 1
     */
    rowsDeleted: number;
}
/**
 * Request to delete multiple categories by their IDs.
 *
 * @generated from protobuf message personal_ledger.CategoriesDeleteBatchRequest
 */
export interface CategoriesDeleteBatchRequest {
    /**
     * @generated from protobuf field: repeated string ids = 1
     */
    ids: string[];
}
/**
 * Response indicating how many categories were deleted in the batch.
 *
 * @generated from protobuf message personal_ledger.CategoriesDeleteBatchResponse
 */
export interface CategoriesDeleteBatchResponse {
    /**
     * @generated from protobuf field: int32 rows_deleted = 1
     */
    rowsDeleted: number;
}
/**
 * Request to activate a category (set is_active = true).
 *
 * @generated from protobuf message personal_ledger.CategoryActivateRequest
 */
export interface CategoryActivateRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * Response containing the activated category.
 *
 * @generated from protobuf message personal_ledger.CategoryActivateResponse
 */
export interface CategoryActivateResponse {
    /**
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Request to deactivate a category (set is_active = false).
 *
 * @generated from protobuf message personal_ledger.CategoryDeactivateRequest
 */
export interface CategoryDeactivateRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * Response containing the deactivated category.
 *
 * @generated from protobuf message personal_ledger.CategoryDeactivateResponse
 */
export interface CategoryDeactivateResponse {
    /**
     * @generated from protobuf field: personal_ledger.Category category = 1
     */
    category?: Category;
}
/**
 * Enum representing the type of financial category.
 * Used to classify categories as assets, liabilities, etc.
 *
 * @generated from protobuf enum personal_ledger.CategoryTypes
 */
export enum CategoryTypes {
    /**
     * Default value. Should not be used.
     *
     * @generated from protobuf enum value: CATEGORY_TYPE_UNSPECIFIED = 0;
     */
    CATEGORY_TYPE_UNSPECIFIED = 0,
    /**
     * Asset category (e.g., cash, property)
     *
     * @generated from protobuf enum value: ASSET = 1;
     */
    ASSET = 1,
    /**
     * Equity category (e.g., owner's equity)
     *
     * @generated from protobuf enum value: EQUITY = 2;
     */
    EQUITY = 2,
    /**
     * Expense category (e.g., groceries, rent)
     *
     * @generated from protobuf enum value: EXPENSE = 3;
     */
    EXPENSE = 3,
    /**
     * Income category (e.g., salary, dividends)
     *
     * @generated from protobuf enum value: INCOME = 4;
     */
    INCOME = 4,
    /**
     * Liability category (e.g., loans, credit cards)
     *
     * @generated from protobuf enum value: LIABILITY = 5;
     */
    LIABILITY = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class Category$Type extends MessageType<Category> {
    constructor() {
        super("personal_ledger.Category", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "url_slug", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "category_type", kind: "enum", T: () => ["personal_ledger.CategoryTypes", CategoryTypes] },
            { no: 7, name: "color", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "icon", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "is_active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "created_on", kind: "message", T: () => Timestamp },
            { no: 11, name: "updated_on", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Category>): Category {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.code = "";
        message.name = "";
        message.categoryType = 0;
        message.isActive = false;
        if (value !== undefined)
            reflectionMergePartial<Category>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Category): Category {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string code */ 2:
                    message.code = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* optional string description */ 4:
                    message.description = reader.string();
                    break;
                case /* optional string url_slug */ 5:
                    message.urlSlug = reader.string();
                    break;
                case /* personal_ledger.CategoryTypes category_type */ 6:
                    message.categoryType = reader.int32();
                    break;
                case /* optional string color */ 7:
                    message.color = reader.string();
                    break;
                case /* optional string icon */ 8:
                    message.icon = reader.string();
                    break;
                case /* bool is_active */ 9:
                    message.isActive = reader.bool();
                    break;
                case /* google.protobuf.Timestamp created_on */ 10:
                    message.createdOn = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdOn);
                    break;
                case /* google.protobuf.Timestamp updated_on */ 11:
                    message.updatedOn = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedOn);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Category, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string code = 2; */
        if (message.code !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.code);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* optional string description = 4; */
        if (message.description !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* optional string url_slug = 5; */
        if (message.urlSlug !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.urlSlug);
        /* personal_ledger.CategoryTypes category_type = 6; */
        if (message.categoryType !== 0)
            writer.tag(6, WireType.Varint).int32(message.categoryType);
        /* optional string color = 7; */
        if (message.color !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.color);
        /* optional string icon = 8; */
        if (message.icon !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.icon);
        /* bool is_active = 9; */
        if (message.isActive !== false)
            writer.tag(9, WireType.Varint).bool(message.isActive);
        /* google.protobuf.Timestamp created_on = 10; */
        if (message.createdOn)
            Timestamp.internalBinaryWrite(message.createdOn, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_on = 11; */
        if (message.updatedOn)
            Timestamp.internalBinaryWrite(message.updatedOn, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.Category
 */
export const Category = new Category$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryCreateRequest$Type extends MessageType<CategoryCreateRequest> {
    constructor() {
        super("personal_ledger.CategoryCreateRequest", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryCreateRequest>): CategoryCreateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryCreateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryCreateRequest): CategoryCreateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryCreateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryCreateRequest
 */
export const CategoryCreateRequest = new CategoryCreateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryCreateResponse$Type extends MessageType<CategoryCreateResponse> {
    constructor() {
        super("personal_ledger.CategoryCreateResponse", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryCreateResponse>): CategoryCreateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryCreateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryCreateResponse): CategoryCreateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryCreateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryCreateResponse
 */
export const CategoryCreateResponse = new CategoryCreateResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryGetRequest$Type extends MessageType<CategoryGetRequest> {
    constructor() {
        super("personal_ledger.CategoryGetRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryGetRequest>): CategoryGetRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryGetRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryGetRequest): CategoryGetRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryGetRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryGetRequest
 */
export const CategoryGetRequest = new CategoryGetRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryGetResponse$Type extends MessageType<CategoryGetResponse> {
    constructor() {
        super("personal_ledger.CategoryGetResponse", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryGetResponse>): CategoryGetResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryGetResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryGetResponse): CategoryGetResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryGetResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryGetResponse
 */
export const CategoryGetResponse = new CategoryGetResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryGetByCodeRequest$Type extends MessageType<CategoryGetByCodeRequest> {
    constructor() {
        super("personal_ledger.CategoryGetByCodeRequest", [
            { no: 1, name: "code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryGetByCodeRequest>): CategoryGetByCodeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.code = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryGetByCodeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryGetByCodeRequest): CategoryGetByCodeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string code */ 1:
                    message.code = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryGetByCodeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string code = 1; */
        if (message.code !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.code);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryGetByCodeRequest
 */
export const CategoryGetByCodeRequest = new CategoryGetByCodeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryGetByCodeResponse$Type extends MessageType<CategoryGetByCodeResponse> {
    constructor() {
        super("personal_ledger.CategoryGetByCodeResponse", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryGetByCodeResponse>): CategoryGetByCodeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryGetByCodeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryGetByCodeResponse): CategoryGetByCodeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryGetByCodeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryGetByCodeResponse
 */
export const CategoryGetByCodeResponse = new CategoryGetByCodeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryGetBySlugRequest$Type extends MessageType<CategoryGetBySlugRequest> {
    constructor() {
        super("personal_ledger.CategoryGetBySlugRequest", [
            { no: 1, name: "url_slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryGetBySlugRequest>): CategoryGetBySlugRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.urlSlug = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryGetBySlugRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryGetBySlugRequest): CategoryGetBySlugRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url_slug */ 1:
                    message.urlSlug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryGetBySlugRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url_slug = 1; */
        if (message.urlSlug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.urlSlug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryGetBySlugRequest
 */
export const CategoryGetBySlugRequest = new CategoryGetBySlugRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryGetBySlugResponse$Type extends MessageType<CategoryGetBySlugResponse> {
    constructor() {
        super("personal_ledger.CategoryGetBySlugResponse", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryGetBySlugResponse>): CategoryGetBySlugResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryGetBySlugResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryGetBySlugResponse): CategoryGetBySlugResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryGetBySlugResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryGetBySlugResponse
 */
export const CategoryGetBySlugResponse = new CategoryGetBySlugResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoriesListRequest$Type extends MessageType<CategoriesListRequest> {
    constructor() {
        super("personal_ledger.CategoriesListRequest", [
            { no: 1, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "category_type", kind: "enum", opt: true, T: () => ["personal_ledger.CategoryTypes", CategoryTypes] },
            { no: 4, name: "is_active", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "sort_by", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "sort_desc", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CategoriesListRequest>): CategoriesListRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offset = 0;
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<CategoriesListRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoriesListRequest): CategoriesListRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 offset */ 1:
                    message.offset = reader.int32();
                    break;
                case /* int32 limit */ 2:
                    message.limit = reader.int32();
                    break;
                case /* optional personal_ledger.CategoryTypes category_type */ 3:
                    message.categoryType = reader.int32();
                    break;
                case /* optional bool is_active */ 4:
                    message.isActive = reader.bool();
                    break;
                case /* optional string sort_by */ 5:
                    message.sortBy = reader.string();
                    break;
                case /* optional bool sort_desc */ 6:
                    message.sortDesc = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoriesListRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 offset = 1; */
        if (message.offset !== 0)
            writer.tag(1, WireType.Varint).int32(message.offset);
        /* int32 limit = 2; */
        if (message.limit !== 0)
            writer.tag(2, WireType.Varint).int32(message.limit);
        /* optional personal_ledger.CategoryTypes category_type = 3; */
        if (message.categoryType !== undefined)
            writer.tag(3, WireType.Varint).int32(message.categoryType);
        /* optional bool is_active = 4; */
        if (message.isActive !== undefined)
            writer.tag(4, WireType.Varint).bool(message.isActive);
        /* optional string sort_by = 5; */
        if (message.sortBy !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.sortBy);
        /* optional bool sort_desc = 6; */
        if (message.sortDesc !== undefined)
            writer.tag(6, WireType.Varint).bool(message.sortDesc);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoriesListRequest
 */
export const CategoriesListRequest = new CategoriesListRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoriesListResponse$Type extends MessageType<CategoriesListResponse> {
    constructor() {
        super("personal_ledger.CategoriesListResponse", [
            { no: 1, name: "categories", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Category },
            { no: 2, name: "total_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CategoriesListResponse>): CategoriesListResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.categories = [];
        message.totalCount = 0;
        message.offset = 0;
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<CategoriesListResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoriesListResponse): CategoriesListResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated personal_ledger.Category categories */ 1:
                    message.categories.push(Category.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 total_count */ 2:
                    message.totalCount = reader.int32();
                    break;
                case /* int32 offset */ 3:
                    message.offset = reader.int32();
                    break;
                case /* int32 limit */ 4:
                    message.limit = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoriesListResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated personal_ledger.Category categories = 1; */
        for (let i = 0; i < message.categories.length; i++)
            Category.internalBinaryWrite(message.categories[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 total_count = 2; */
        if (message.totalCount !== 0)
            writer.tag(2, WireType.Varint).int32(message.totalCount);
        /* int32 offset = 3; */
        if (message.offset !== 0)
            writer.tag(3, WireType.Varint).int32(message.offset);
        /* int32 limit = 4; */
        if (message.limit !== 0)
            writer.tag(4, WireType.Varint).int32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoriesListResponse
 */
export const CategoriesListResponse = new CategoriesListResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryUpdateRequest$Type extends MessageType<CategoryUpdateRequest> {
    constructor() {
        super("personal_ledger.CategoryUpdateRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "category", kind: "message", T: () => Category },
            { no: 3, name: "update_mask", kind: "message", T: () => FieldMask }
        ]);
    }
    create(value?: PartialMessage<CategoryUpdateRequest>): CategoryUpdateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryUpdateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryUpdateRequest): CategoryUpdateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* personal_ledger.Category category */ 2:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                case /* google.protobuf.FieldMask update_mask */ 3:
                    message.updateMask = FieldMask.internalBinaryRead(reader, reader.uint32(), options, message.updateMask);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryUpdateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* personal_ledger.Category category = 2; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.FieldMask update_mask = 3; */
        if (message.updateMask)
            FieldMask.internalBinaryWrite(message.updateMask, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryUpdateRequest
 */
export const CategoryUpdateRequest = new CategoryUpdateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryUpdateResponse$Type extends MessageType<CategoryUpdateResponse> {
    constructor() {
        super("personal_ledger.CategoryUpdateResponse", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryUpdateResponse>): CategoryUpdateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryUpdateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryUpdateResponse): CategoryUpdateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryUpdateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryUpdateResponse
 */
export const CategoryUpdateResponse = new CategoryUpdateResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoriesCreateBatchRequest$Type extends MessageType<CategoriesCreateBatchRequest> {
    constructor() {
        super("personal_ledger.CategoriesCreateBatchRequest", [
            { no: 1, name: "categories", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoriesCreateBatchRequest>): CategoriesCreateBatchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.categories = [];
        if (value !== undefined)
            reflectionMergePartial<CategoriesCreateBatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoriesCreateBatchRequest): CategoriesCreateBatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated personal_ledger.Category categories */ 1:
                    message.categories.push(Category.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoriesCreateBatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated personal_ledger.Category categories = 1; */
        for (let i = 0; i < message.categories.length; i++)
            Category.internalBinaryWrite(message.categories[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoriesCreateBatchRequest
 */
export const CategoriesCreateBatchRequest = new CategoriesCreateBatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoriesCreateBatchResponse$Type extends MessageType<CategoriesCreateBatchResponse> {
    constructor() {
        super("personal_ledger.CategoriesCreateBatchResponse", [
            { no: 1, name: "categories", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Category },
            { no: 2, name: "created_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CategoriesCreateBatchResponse>): CategoriesCreateBatchResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.categories = [];
        message.createdCount = 0;
        if (value !== undefined)
            reflectionMergePartial<CategoriesCreateBatchResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoriesCreateBatchResponse): CategoriesCreateBatchResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated personal_ledger.Category categories */ 1:
                    message.categories.push(Category.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 created_count */ 2:
                    message.createdCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoriesCreateBatchResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated personal_ledger.Category categories = 1; */
        for (let i = 0; i < message.categories.length; i++)
            Category.internalBinaryWrite(message.categories[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 created_count = 2; */
        if (message.createdCount !== 0)
            writer.tag(2, WireType.Varint).int32(message.createdCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoriesCreateBatchResponse
 */
export const CategoriesCreateBatchResponse = new CategoriesCreateBatchResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryDeleteRequest$Type extends MessageType<CategoryDeleteRequest> {
    constructor() {
        super("personal_ledger.CategoryDeleteRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryDeleteRequest>): CategoryDeleteRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryDeleteRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryDeleteRequest): CategoryDeleteRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryDeleteRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryDeleteRequest
 */
export const CategoryDeleteRequest = new CategoryDeleteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryDeleteResponse$Type extends MessageType<CategoryDeleteResponse> {
    constructor() {
        super("personal_ledger.CategoryDeleteResponse", [
            { no: 1, name: "rows_deleted", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryDeleteResponse>): CategoryDeleteResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rowsDeleted = 0;
        if (value !== undefined)
            reflectionMergePartial<CategoryDeleteResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryDeleteResponse): CategoryDeleteResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 rows_deleted */ 1:
                    message.rowsDeleted = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryDeleteResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 rows_deleted = 1; */
        if (message.rowsDeleted !== 0)
            writer.tag(1, WireType.Varint).int32(message.rowsDeleted);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryDeleteResponse
 */
export const CategoryDeleteResponse = new CategoryDeleteResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoriesDeleteBatchRequest$Type extends MessageType<CategoriesDeleteBatchRequest> {
    constructor() {
        super("personal_ledger.CategoriesDeleteBatchRequest", [
            { no: 1, name: "ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoriesDeleteBatchRequest>): CategoriesDeleteBatchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ids = [];
        if (value !== undefined)
            reflectionMergePartial<CategoriesDeleteBatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoriesDeleteBatchRequest): CategoriesDeleteBatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string ids */ 1:
                    message.ids.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoriesDeleteBatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string ids = 1; */
        for (let i = 0; i < message.ids.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.ids[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoriesDeleteBatchRequest
 */
export const CategoriesDeleteBatchRequest = new CategoriesDeleteBatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoriesDeleteBatchResponse$Type extends MessageType<CategoriesDeleteBatchResponse> {
    constructor() {
        super("personal_ledger.CategoriesDeleteBatchResponse", [
            { no: 1, name: "rows_deleted", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CategoriesDeleteBatchResponse>): CategoriesDeleteBatchResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rowsDeleted = 0;
        if (value !== undefined)
            reflectionMergePartial<CategoriesDeleteBatchResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoriesDeleteBatchResponse): CategoriesDeleteBatchResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 rows_deleted */ 1:
                    message.rowsDeleted = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoriesDeleteBatchResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 rows_deleted = 1; */
        if (message.rowsDeleted !== 0)
            writer.tag(1, WireType.Varint).int32(message.rowsDeleted);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoriesDeleteBatchResponse
 */
export const CategoriesDeleteBatchResponse = new CategoriesDeleteBatchResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryActivateRequest$Type extends MessageType<CategoryActivateRequest> {
    constructor() {
        super("personal_ledger.CategoryActivateRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryActivateRequest>): CategoryActivateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryActivateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryActivateRequest): CategoryActivateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryActivateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryActivateRequest
 */
export const CategoryActivateRequest = new CategoryActivateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryActivateResponse$Type extends MessageType<CategoryActivateResponse> {
    constructor() {
        super("personal_ledger.CategoryActivateResponse", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryActivateResponse>): CategoryActivateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryActivateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryActivateResponse): CategoryActivateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryActivateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryActivateResponse
 */
export const CategoryActivateResponse = new CategoryActivateResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryDeactivateRequest$Type extends MessageType<CategoryDeactivateRequest> {
    constructor() {
        super("personal_ledger.CategoryDeactivateRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryDeactivateRequest>): CategoryDeactivateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryDeactivateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryDeactivateRequest): CategoryDeactivateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryDeactivateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryDeactivateRequest
 */
export const CategoryDeactivateRequest = new CategoryDeactivateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryDeactivateResponse$Type extends MessageType<CategoryDeactivateResponse> {
    constructor() {
        super("personal_ledger.CategoryDeactivateResponse", [
            { no: 1, name: "category", kind: "message", T: () => Category }
        ]);
    }
    create(value?: PartialMessage<CategoryDeactivateResponse>): CategoryDeactivateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CategoryDeactivateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryDeactivateResponse): CategoryDeactivateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* personal_ledger.Category category */ 1:
                    message.category = Category.internalBinaryRead(reader, reader.uint32(), options, message.category);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryDeactivateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* personal_ledger.Category category = 1; */
        if (message.category)
            Category.internalBinaryWrite(message.category, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message personal_ledger.CategoryDeactivateResponse
 */
export const CategoryDeactivateResponse = new CategoryDeactivateResponse$Type();
/**
 * @generated ServiceType for protobuf service personal_ledger.CategoriesService
 */
export const CategoriesService = new ServiceType("personal_ledger.CategoriesService", [
    { name: "CategoryCreate", options: {}, I: CategoryCreateRequest, O: CategoryCreateResponse },
    { name: "CategoriesCreateBatch", options: {}, I: CategoriesCreateBatchRequest, O: CategoriesCreateBatchResponse },
    { name: "CategoryGet", options: {}, I: CategoryGetRequest, O: CategoryGetResponse },
    { name: "CategoryGetByCode", options: {}, I: CategoryGetByCodeRequest, O: CategoryGetByCodeResponse },
    { name: "CategoryGetBySlug", options: {}, I: CategoryGetBySlugRequest, O: CategoryGetBySlugResponse },
    { name: "CategoriesList", options: {}, I: CategoriesListRequest, O: CategoriesListResponse },
    { name: "CategoryUpdate", options: {}, I: CategoryUpdateRequest, O: CategoryUpdateResponse },
    { name: "CategoryDelete", options: {}, I: CategoryDeleteRequest, O: CategoryDeleteResponse },
    { name: "CategoriesDeleteBatch", options: {}, I: CategoriesDeleteBatchRequest, O: CategoriesDeleteBatchResponse },
    { name: "CategoryActivate", options: {}, I: CategoryActivateRequest, O: CategoryActivateResponse },
    { name: "CategoryDeactivate", options: {}, I: CategoryDeactivateRequest, O: CategoryDeactivateResponse }
]);
