// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "utilities.proto" (package "personal_ledger", syntax proto3)
// tslint:disable
//
//-- ./proto/utilities.proto
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UtilitiesService } from "./utilities";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PingResponse } from "./utilities";
import type { PingRequest } from "./utilities";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * The Utilities service definition.
 *
 * @generated from protobuf service personal_ledger.UtilitiesService
 */
export interface IUtilitiesServiceClient {
    /**
     * @generated from protobuf rpc: Ping
     */
    ping(input: PingRequest, options?: RpcOptions): UnaryCall<PingRequest, PingResponse>;
}
/**
 * The Utilities service definition.
 *
 * @generated from protobuf service personal_ledger.UtilitiesService
 */
export class UtilitiesServiceClient implements IUtilitiesServiceClient, ServiceInfo {
    typeName = UtilitiesService.typeName;
    methods = UtilitiesService.methods;
    options = UtilitiesService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Ping
     */
    ping(input: PingRequest, options?: RpcOptions): UnaryCall<PingRequest, PingResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PingRequest, PingResponse>("unary", this._transport, method, opt, input);
    }
}
